name: Daily Slackbot Message

on:
  schedule:
    # Standard time (last Sunday in October to last Saturday in March)
      - cron: '30 15 * * 1-5'
    
    # Daylight saving time (last Sunday in March to last Saturday in October)
      - cron: '30 14 * * 1-5'

jobs:
  send-message:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install slack-sdk

    - name: Run the script
      run: python ./app.py
      env:
        SLACK_API_TOKEN: ${{ secrets.SLACK_API_TOKEN }}
        SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_ID }}
